services:
  fullstack-app:
    build:
      context: ./fullstack
    restart: always
    ports:
      - "3000:3000" 
    env_file:
      - ./fullstack/.env

  python:
    build:
      context: python-backend
    restart: always
    ports:
      - "8000:8000"