version: '3.8'

services:
  fullstack-app:
    build:
      context: ./fullstack
    restart: always
    ports:
      - "3000:3000" 
    networks:
      - app-network
    environment:
      - NODE_ENV=production 

networks:
  app-network:
    driver: bridge
