version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "42335:42335"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
