version: '3.8'

services:
  backend:
    build:
      context: ./fullstack
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge