name: Replace Secret Placeholder

on:
  push:
    branches:
      - sc-test-sensor
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace Secret Placeholder
      run: |
        sed -i 's/FEATHER_PLACEHOLDER/${{ secrets.FEATHER_F6 }}/g' Cloudy-with-a-Chance-of-LoRa/feather_sensors/sensor_f6/Secrets.h
