name: Build and Upload Arduino

on:
  push:
    branches:
      - sc-test-sensor
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List Directory Structure
      run: |
        ls -R
        # List specific directory to verify file location
        ls Cloudy-with-a-Chance-of-LoRa/feather_sensors/sensor_f6