name: Replace Secret Placeholder

on:
  push:
    branches:
      - sc-test-sensor
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace Secret Placeholder F6
      run: |
        sed -i 's/FEATHER_PLACEHOLDER/${{ secrets.FEATHER_F6 }}/g' feather_sensors/sensor_f6/Secrets.h
        
    - name: Replace Secret Placeholder F5
      run: |
        sed -i 's/FEATHER_PLACEHOLDER/${{ secrets.FEATHER_F5 }}/g' feather_sensors/sensor_f5/Secrets.h
