# name: Replace Secret Placeholder

# on:
#   push:
#     branches:
#       - sc-test-sensor
#   workflow_dispatch:

# jobs:
#   update-secrets:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#   - name: Replace Secret Placeholder F6
#         run: |
#           echo "Replacing FEATHER_PLACEHOLDER with secret F6 in sensor_f6"
#           sed -i 's/FEATHER_PLACEHOLDER/${{ secrets.FEATHER_F6 }}/g' feather_sensors/sensor_f6/Secrets.h
          
#   - name: Replace Secret Placeholder F5
#         run: |
#           echo "Replacing FEATHER_PLACEHOLDER with secret F5 in sensor_f5"
#           sed -i 's/FEATHER_PLACEHOLDER/${{ secrets.FEATHER_F5 }}/g' feather_sensors/sensor_f5/Secrets.h

  
#   - name: Configure Arduino CLI
#       run: |
#         arduino-cli config init
#         arduino-cli core update-index
#         arduino-cli core install arduino:avr

#     - name: Build Arduino Sketch
#       run: |
#         arduino-cli compile --fqbn arduino:avr:uno feather_sensors/sensor_f6

#     - name: List Serial Ports
#       run: |
#         ls /dev/tty*

#     - name: Upload to Arduino
#       run: |
#         arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:uno feather_sensors/sensor_f6